### ISSUE TITLE
Will this be proposed to the boost library?

### ISSUE THREAD

**Issue by dirkarnez** [cycfi/elements#214]
Just curious 🤣

**Comment by djowel** [comment]
I've been asked before. Maybe in the future.

**Comment by dirkarnez** [comment]
Wow, that is amazing. Just love the modularity this slim library achieves, also the declarative style. Wish I can learn and contribute to this project.

Shall I start with creating new elements by composing the existing ones? And does this library love View Model in modular form? 

Thank you @djowel !

**Comment by djowel** [comment]
Thank you, @dirkarnez. Much appreciated. I have a few libraries already in Boost (Spirit, Fusion and Phoenix). I have to say, I miss Boost a lot. The developers there are among the very best, and it was really a pleasure collaborating with Boost folks.

We're still not "production ready", but we're getting closer to 1.0. If you want to contribute, I'd say start by playing around with the components and get to know it well. As I said in the front page: more people using it will ultimately make it more robust when bugs are reported and fixed. So, I welcome bug reports like you did recently.

The API might be changing still, so I suggest joining the [discord channel](https://discord.gg/NJkadSx) and hang out with the developers.

**Comment by dirkarnez** [comment]
Thank you @djowel, I see, going to trying these components out 😉

**Comment by Xeverous** [comment]
@dirkarnez I don't think this library is (at least now) a good candicate for boost. Joel's design goals are pretty minimal and boost generally wants maximum customizability (just read [beast's comparison and rationale](https://www.boost.org/doc/libs/1_74_0/libs/beast/doc/html/beast/design_choices/http_comparison_to_other_librari.html) as an example). I disagree with Joel on some fundamental things like event handling and OS abstractions and IMO, from boost's perspective a library like this would need to offer much broader abstractions (even if it means a no-op on some OS due to lack of support) and more hooks for custom code (such as editing events).

Also, this library no longer requires any boost libraries. I think that keeping such projects standalone is better - why mix it with huge dependency when there is no need to? I don't even see any significant improvements if elements was to utilize some boost functionality inside.
