### ISSUE TITLE
Asio dependency causing problems with C++-23 and clang

### ISSUE THREAD

**Issue by bruno-j-nicoletti** [cycfi/elements#379]
Due to a dependency on the `asio` library, elements refuses to build with clang-17 and C++-23 due to a missing `<exceptions>` include header in asio. I currently get around this by patching the asio sources in the submodule.

Asio it self is a massive library, and only a small bit is being used for the event loop. Would you consider either flipping out asio for a different library? Or better still, to abstract out the event loop so a different async lib could be used? This would be important for any future webassembly/HTML backend.

**Comment by djowel** [comment]
It might be a good idea to abstract out the event loop so a different async lib. But do you know any library similar in functionality to the executors (**) as asio? Asio is not really massive, because you only pay for what you use. For one, it is header only.

Is the missing <exceptions> problem still in the latest code of ASIO?

(** Asio provides a complete implementation of the proposed standard executors that I do not see anywhere else)

**Comment by bruno-j-nicoletti** [comment]
If I flip to the tag `asio-1-29-0` it fixes it. 

How will you interact with a webasm/HTML event loop though? Which is the main reason why I was suggesting the abstraction. But that can wait until a webasm/HTML back end is written.

**Comment by redtide** [comment]
Just for references: chriskohlhoff/asio#387, chriskohlhoff/asio#532 and chriskohlhoff/asio#643.

**Comment by djowel** [comment]
Fixed in c60c2993c8e75f3b5d9b87a61099e3c835b365d6
