### ISSUE TITLE
Coding conventions

### ISSUE THREAD

**Issue by phicore** [cycfi/elements#5]
looking at the source code I saw that you are using some conventions I don't know about

example 

```
int main(int argc, const char* argv[])
{
   app _app(argc, argv);
   window _win(_app.name());
   _win.on_close = [&_app]() { _app.stop(); };

   view view_(_win);

   view_.content(
      {
         share(make_controls(view_)),
         share(background)
      }
   );

   _app.run();
   return 0;
}
```
 

What is the purpose of prefixing or post fixing with underscores?

Maybe you can point out to a document or webpage describing your coding style.

Thanks

**Comment by Xeverous** [comment]
`_` or `m_` prefix is commonly used for member variables, but I don't get this either.

Also, @djowel is the author of Boost Spirit library which uses `foo_` thorougly to avoid name clashes with keywords.

**Comment by djowel** [comment]
For member variables, esp. private, and local variables, I use the prefix underscore. Typically to avoid name clashes. For example, you might have a member named _size and a member function accessor named size() const. In the example above, since you already have an "app" class, I simply use _app for an instance of that class. You can use my_app or whatever, it does not really matter. I also used _win, in this case, for consistency, although I do not have to because there's no name clash.

For simple structs, I use no pre/post underscores. For arguments and local variables that can have name conflicts, I sometimes use the post-underscore. These are the naming "conventions" I've been using since the early Boost days and I stuck to it. I should probably document that somewhere. To be honest, I'd say just use whatever works for you.

**Comment by phicore** [comment]
Thanks, I was just curious about it.
