### ISSUE TITLE
Investigate the possibility of cross-graphics support with A Skia backend

### ISSUE THREAD

**Issue by djowel** [cycfi/elements#72]
I've been following the Cairo roadmap for quite some time (https://www.cairographics.org/roadmap/). At one point, Elements actually used NanoVG as the 2D graphics backend. It supported things like blurred drop-shadows that had to be poorly simulated in the switch to Cairo. So I was anticipating support for optimized gaussian blur effect as listed in the Cairo roadmap, supposedly targeted for cairo 1.16 (2017?). It's 2020 now.

And now James Berrow's scorching review of the c++ Cairo based 2D graphics proposal : http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2020/p2005r0.html

I don't quite agree on a lot of things, but it might probably make sense to abstract away the 2d graphics backend.

**Comment by Xeverous** [comment]
As it seems the situation (like with rendering text) is not trivial:

- Reading the proposal it sounds like elements has the same problem of `operator*` which does not behave correctly/consistently. Multiplying separate RGB values is not linear for human vision and there is no clear semantics when the value is higher than 1. As someone who is working with/using/writing/knowing applications that has some color-related UI, I noticed that even mentally multiplying RGB values does very unpredictable color changes and any user gets better results with visual color pickers or HSV/HSL representations.
- I'm very inexperienced with graphics itself, so I don't really care how/what elements uses underneath. The only obvious thing to me is that elements should encapsulate underlying implementation so that user code is not affected when the implementation changes. So far the canvas API does not expose anything apart from accidental cairo includes which users should not reply upon. I understand that cairo does not support many things (including blur) and there are some workarounds but again - I have low knowledge here so I won't really comment on any of your choices.

What are your current plans for the graphics backend? Any planned API or dependency changes?

**Comment by djowel** [comment]
> * So far the canvas API does not expose anything apart from accidental cairo includes which users should not reply upon.

Hopefully, no API changes. That's the main motivation behind the canvas API. That is the crucial part. 

Since 2016, Elements has undergone 3 graphics backend swaps (original OSX only, nanoVG then Cairo) with little impact on user code (some ports here and there because of API changes -- the biggest was the simulation of blur which cairo did not support; also, nanovg had some specific and rather unusual API on some parts). As long as the canvas api is stable, it should be good. It might even be possible to choose different backends.

**Comment by djowel** [comment]
> * Reading the proposal it sounds like elements has the same problem of `operator*` which does not behave correctly/consistently. Multiplying separate RGB values is not linear for human vision and there is no clear semantics when the value is higher than 1. As someone who is working with/using/writing/knowing applications that has some color-related UI, I noticed that even mentally multiplying RGB values does very unpredictable color changes and any user gets better results with visual color pickers or HSV/HSL representations.

Agreed. This one has to change. Do what is right.

**Comment by djowel** [comment]
The result of this is https://github.com/cycfi/artist
