### ISSUE TITLE
Help using elements as a library?

### ISSUE THREAD

**Issue by Radagan** [cycfi/elements#95]
I'm very excited about elements--it's exactly what I've wanted for a very long time! Unfortunately, as I'm pretty new to cmake, I'm having difficulty getting started with a project of my own that uses it.

I've built elements and can run the examples on both Windows 10 and macos--no problem. What I'm trying to figure out is how to define a CMakeLists.txt from my project to use elements as a STATIC IMPORTED library.

My main contains the code from the empty window example, but as of yet fails to compile. Please see output below.

I'm sure I'm doing something silly. A gentle shove in the right direction would be greatly appreciated.

My CMakeLists.txt:
```
cmake_minimum_required(VERSION 3.16 FATAL_ERROR)

project(Multimind LANGUAGES CXX)

set(CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS ON)

add_library(elements STATIC IMPORTED)
set_target_properties(elements
        PROPERTIES
            IMPORTED_LOCATION "../libs/elements/build/lib/elements.lib"
        )

add_library(cairo STATIC IMPORTED)
set_target_properties(cairo
        PROPERTIES
        IMPORTED_LOCATION "../libs/elements/lib/external/cairo/lib/x64/cairo.lib"
        )

add_library(fontconfig STATIC IMPORTED)
set_target_properties(elements
        PROPERTIES
        IMPORTED_LOCATION "../libs/elements/lib/external/fontconfig/x64/fontconfig.lib"
        )

add_library(freetype STATIC IMPORTED)
set_target_properties(elements
        PROPERTIES
        IMPORTED_LOCATION "../libs/elements/lib/external/freetype/win64/freetype.lib"
        )

set(EXEC_SOURCE_FILES
            main.cpp
            Multimind.cpp
        )
add_executable(Multimind ${EXEC_SOURCE_FILES})
set_target_properties(Multimind
        PROPERTIES
            CXX_STANDARD 17
            CXX_EXTENSIONS OFF
            CXX_STANDARD_REQUIRED ON
        )

target_link_libraries(Multimind elements)

include_directories("../libs/elements/lib/include")
include_directories("../libs/elements/lib/infra/include")
include_directories("../libs/elements/lib/external/cairo/include")
include_directories("../libs/elements/lib/external/fontconfig/include")
include_directories("../libs/elements/lib/external/freetype/include")

message(STATUS "Compiler is: " ${CMAKE_CXX_COMPILER_ID})
```

Console output when trying to build:
```
====================[ Build | all | Debug ]=====================================
"C:\Program Files\JetBrains\CLion 2019.3.5\bin\cmake\win\bin\cmake.exe" --build C:\Users\Radagan\Development\cpp\Multimind\cmake-build-debug --target all
Scanning dependencies of target Multimind
[ 33%] Building CXX object CMakeFiles/Multimind.dir/main.cpp.obj
main.cpp
C:\Users\Radagan\Development\cpp\libs\elements\lib\include\elements/base_view.hpp(298): error C2061: syntax error: identifier 'host_window_handle'
C:\Users\Radagan\Development\cpp\libs\elements\lib\include\elements/base_view.hpp(318): error C3646: 'host': unknown override specifier
C:\Users\Radagan\Development\cpp\libs\elements\lib\include\elements/base_view.hpp(318): error C2059: syntax error: '('
C:\Users\Radagan\Development\cpp\libs\elements\lib\include\elements/base_view.hpp(318): error C2334: unexpected token(s) preceding '{'; skipping apparent function body
C:\Users\Radagan\Development\cpp\libs\elements\lib\include\elements/base_view.hpp(322): error C3646: '_view': unknown override specifier
C:\Users\Radagan\Development\cpp\libs\elements\lib\include\elements/base_view.hpp(322): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
C:\Users\Radagan\Development\cpp\libs\elements\lib\include\elements/window.hpp(60): error C3646: 'host': unknown override specifier
C:\Users\Radagan\Development\cpp\libs\elements\lib\include\elements/window.hpp(60): error C2059: syntax error: '('
C:\Users\Radagan\Development\cpp\libs\elements\lib\include\elements/window.hpp(60): error C2334: unexpected token(s) preceding '{'; skipping apparent function body
C:\Users\Radagan\Development\cpp\libs\elements\lib\include\elements/window.hpp(70): error C3646: '_window': unknown override specifier
C:\Users\Radagan\Development\cpp\libs\elements\lib\include\elements/window.hpp(70): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
C:\Users\Radagan\Development\cpp\libs\elements\lib\include\elements/view.hpp(17): fatal error C1083: Cannot open include file: 'boost/asio.hpp': No such file or directory
NMAKE : fatal error U1077: 'C:\PROGRA~2\MICROS~2\2019\COMMUN~1\VC\Tools\MSVC\1425~1.286\bin\Hostx86\x86\cl.exe' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\bin\HostX86\x86\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\bin\HostX86\x86\nmake.exe"' : return code '0x2'
Stop.
```

**Comment by djowel** [comment]
Have a look at. https://github.com/cycfi/elements/issues/89 and see if that works for you. @Xeverous is working on making this easy again.

**Comment by Xeverous** [comment]
> I'm sure I'm doing something silly.

Yes, you are.

> how to define a CMakeLists.txt from my project to use elements as a STATIC IMPORTED library

You **do not want** to use elements as an imported target. **`IMPORTED` targets in CMake are intended for projects which do not support building/using through CMake.** Defining imported target in CMake is for specifying all the project details (after) the project has been build (using its own build system). This is duplicate work when the project already does it in its own CMake recipe.

What you want to do is to take advantage of the fact that elements is already a CMake project and therefore:

a) Include elements into your project by `add_subdirectory()` command (contary to the name, path can be aboslute non-subdirectory too).
b) Include elements into  your project by `find_package()`. For this to work, the searched project must support CMake post-build-package configuration which (in case of elements) I'm doubt to be complete (therefore, prefer a).

Second thing, modern CMake knows of transitive dependencies. If library A uses library B, then a library X which uses A will automatically get B too. If not, then report a bug to A that its transitive dependencies (`PUBLIC` or `INTERFACE`  instead of `PRIVATE`) are not correctly exposed in its recipe. Therefore, if you use elements you should not need to specify any of its dependencies like freetype or cairo.

Last thing - avoid using deprecated CMake commands. Modern CMake is all about targets and their properties, no global flags. Never use a command line `include_directories`, use `target_include_directories` for specific target and specify whether it is a usage or build requirement (`INTERFACE` or `PRIVATE` respectively; or `PUBLIC` in case of both). You also missed these keywords in the `target_link_libraries` command, which (for backwards compatibility) supports keyword-less usage, but corrupts all futher linking in modern CMake.

You may find these useful:

https://pabloariasal.github.io/2018/02/19/its-time-to-do-cmake-right/
https://cliutils.gitlab.io/modern-cmake/

**Comment by djowel** [comment]
@Xeverous The intent of the examples, esp. the starter example, is to make it easy to use Elements, by simply copying the example somewhere and adjusting a link. To be honest, I do not care much about cmake, or modern cmake for that matter. To me, it's just a tool. What I care about more is easy setup for users. I do not want a user to spend more than 1 minute to deploy the starter application.

**Comment by Xeverous** [comment]
I care a lot about CMake because apart from it being a tool, it is code and code should be treated seriously (I have autogenerated build code as much as autogenerated C++).

In terms of easy setup, modern CMake is the way to go. One of the significant advantages is that modern CMake recursively takes care of transitive dependencies. One call to `target_link_libraries` should fill all dependency info and the rest is for the project itself. Elements examples in the current form (including `CMakeMain.txt` + many variables) create some unnecessary load for readers.

This is a minimal sample executable recipe using elements:

```cmake
cmake_minimum_required(VERSION 3.13...3.16)
project(my_proj)

if (ELEMENTS_LIBRARY_ROOT)
        add_subdirectory(${ELEMENTS_LIBRARY_ROOT} ${CMAKE_BINARY_DIR}/elements)
else()
        message(FATAL_ERROR "ELEMENTS_LIBRARY_ROOT is not set")
endif()

add_executable(my_proj)

target_sources(my_proj
        PRIVATE
                main.cpp
)

target_include_directories(my_proj
        PRIVATE
                ${CMAKE_CURRENT_SOURCE_DIR}
)

target_compile_features(my_proj
        PRIVATE
                cxx_std_17
)

target_compile_options(my_proj
        PRIVATE
                $<$<CXX_COMPILER_ID:GNU>:-Wall -Wextra -Wpedantic>
                $<$<CXX_COMPILER_ID:Clang>:-Wall -Wpedantic>
                $<$<CXX_COMPILER_ID:MSVC>:/W4>
)

target_link_libraries(my_proj
        PRIVATE
                cycfi::elements
)
```

**Comment by djowel** [comment]
Looks fine to me, except for the excessive spaces/tabs :-)

It's not as clean and easy as the original though:

```
set(ELEMENTS_APP_PROJECT "EmptyStarter")
set(ELEMENTS_APP_TITLE "Empty Starter")
set(ELEMENTS_APP_COPYRIGHT "Copyright (c) 2016-2020 Joel de Guzman")
set(ELEMENTS_APP_ID "com.cycfi.empty-starter")
set(ELEMENTS_APP_VERSION "1.0")
include("../some-path-to-elements/CMakeMain.txt")
```

Also, what about the required  ELEMENTS_* variables?

**Comment by Xeverous** [comment]
Well, the excessive whitespace is because I copied it from my project which has rather big recipe (with multiple libraries) so I nest keywords like this:

```cmake
target_sources(proj
	PRIVATE
		main.cpp
		...
	PUBLIC
		header.hpp
		...
)
```

I don't find the library examples to be very clean because while the recipe looks simple, the included file is full of variables. I would rather make a separate (complete) recipe in each example directory.

**Comment by djowel** [comment]
> I don't find the library examples to be very clean because while the recipe looks simple, the included file is full of variables. I would rather make a separate (complete) recipe in each example directory.

I am not sure I am convinced. CMake expertise is not a requirement to use the library. Of course, if you are a CMake expert like yourself, you are always free to write more elaborate CMake scripts. To me, CMake is just an necessary tool, but I am not too much a fan of. I only use what I need.

**Comment by djowel** [comment]
> I don't find the library examples to be very clean because while the recipe looks simple, the included file is full of variables. I would rather make a separate (complete) recipe in each example directory.

The more I think about it, the more I am not convinced with what you are proposing. So basically, you want to get rid of the included cmake file and have each one in its separate directories with lots of boiler-plate code duplicated in each cmake file. That totally goes against DRY principle. A fundamental change to one file will require you to change all the files using copy paste. Not good! 

If only cmake has templates, but of course it does not. The include file trick and dynamic scoping is the closest you can get to templates in cmake.

**Comment by Radagan** [comment]
@Xeverous, Thank you so very much! Really, thank you for taking the time to spell out the details of where I've gone off. And thank you for the links! The CMake documentation is much like finding ones way through a forest, "Okay, that tree there is a oak, but what county are we in--which way is North?" Lots of details, but very few general guidelines.

@djowel, I support Xeverous on CMake's importance. Please don't take my difficulty with it as a criticism of its value. It is more and more a critical skill to have. CMake is a builder of build systems, which enables a high level of platform flexibility from a general build syntax. For a cross-platform library like elements, CMake support is a feature in and of itself for the library. Even, if, um... I'm just learning to properly use it. I just found elements after struggling with Skia... When I saw that elements supported my targets, C++17, and then saw it was CMake based? I went for coffee and told my wife! 

If the goal is to be up and going in a minute--and that's a very nice goal--all you would have to do is create an example CMake project that does so with one of the examples, then put it in a separate repo. Sort of an elements "best practices" example.

**Comment by Radagan** [comment]
> The more I think about it, the more I am not convinced with what you are proposing. So basically, you want to get rid of the included cmake file and have each one in its separate directories with lots of boiler-plate code duplicated in each cmake file. That totally goes against DRY principle. A fundamental change to one file will require you to change all the files using copy paste. Not good!

It depends on your goal. Aren't the examples intended to be starting points for new users of the library? If so, who cares about code duplication, my desire is for the example to be completely independent of the library's internals, so in that sense it's not a duplication of code--it's adding clarity to what is important for me to understand in order to **use** elements as a library. I'm sure I'll get around to wanting to add to it, which is why I forked it, but not day one.

**Comment by djowel** [comment]
> @djowel, I support Xeverous on CMake's importance. Please don't take my difficulty with it as a criticism of its value. It is more and more a critical skill to have. CMake is a builder of build systems, which enables a high level of platform flexibility from a general build syntax. For a cross-platform library like elements, CMake support is a feature in and of itself for the library. Even, if, um... I'm just learning to properly use it. I just found elements after struggling with Skia... When I saw that elements supported my targets, C++17, and then saw it was CMake based? I went for coffee and told my wife!

I agree of CMake's importance. I don't agree on the "right" way to use it in the case for examples. As I mentioned, what @Xeverous is proposing goes against the DRY principle by having LOTS of code duplication in each of the examples. I'd prefer to think outside the box rather than following a set of "holy" rules on how to use a tool.

Convince me otherwise if I am wrong. But please don't force something on me just because it is the "right" way of doing things. Show me the merits and the disadvantages rather than links to articles purporting how things should be. I am not a rule follower and I often go against the rules.

**Comment by djowel** [comment]
> If so, who cares about code duplication

I care. There's a reason for the DRY principle. For example, less maintenance headaches. Moreover, the examples are not meant to teach cmake. It is meant to teach Elements!  And as such it should not take more than 1 minute to have it deployed. That is an important requirement. I want libraries that are easy to build and deploy!

> Aren't the examples intended to be starting points for new users of the library? If so, who cares about code duplication, my desire is for the example to be completely independent of the library's internals, so in that sense it's not a duplication of code--it's adding clarity to what is important for me to understand in order to **use** elements as a library. I'm sure I'll get around to wanting to add to it, which is why I forked it, but not day one.

That is a very valid statement. I can agree on that, but only if it does not violate the first requirement I mentioned.

**Comment by Xeverous** [comment]
> Aren't the examples intended to be starting points for new users of the library? If so, who cares about code duplication, my desire is for the example to be completely independent of the library's internals, so in that sense it's not a duplication of code--it's adding clarity to what is important for me to understand in order to use elements as a library.

I agree with this. @Radagan you can read the discussion on https://gitlab.com/CLIUtils/modern-cmake/-/issues/24 - there are some good arguments against the current implementation of examples in elements. Each example is a separate mini-project and therefore it should not be considered code duplication. It's like changing `constexpr auto foo = 123; constexpr auto bar = 123;` to have `constexpr auto bar = foo;` while in fact both values are totally separate things and therefore should not be considered to have duplicated code of `123`.

**Comment by djowel** [comment]
Bottom line: tell me why having variables and cmake include is wrong and if there's valid compelling reasons against it other than "unnecessary load for readers", I might change my mind. As it stands: "unnecessary load for readers" vs. DRY. I'll choose for the latter anytime. It's the same as c++ templates. They are ugly, but they eliminate code duplication.

**Comment by Radagan** [comment]
> > If so, who cares about code duplication
> 
> I care.

Okay, I actually care too. Code duplication is "false laziness". I admit it. And I'm not advocating following CMake rules just to be following them. 

But consider myself as an example: I barely know what the CMake rules are, so that's not my point. When I started trying to sort out your CMakeMain.txt and pull one of the examples out, I ended up opening an issue, which really wasn't one. It was a question of "How do I really get started here?" I think for examples to be real examples, they should not rely on the library code base. Skia has the very same issue, but even more so. Building it and running the examples is easy. Try to use it as an external library? Try to pull one of those neat examples out of the Skia project and just use it? Your going to need to know a lot more about how the library works. This sort of thing drops the new user squarely on his head. I think Google wants to discourage use of Skia outside there ecosystem to some extent, but I know that's not your intent at all.

**Comment by djowel** [comment]
> But consider myself as an example: I barely know what the CMake rules are, so that's not my point. When I started trying to sort out your CMakeMain.txt and pull one of the examples out, I ended up opening an issue, which really wasn't one. It was a question of "How do I really get started here?" 

The reason is because the current setup is broken and the docs that guide the users on how to use the examples are not complete (work in progress). There's a setup guide and it should be complete up to the point of deployment

> I think for examples to be real examples, they should not rely on the library code base. Skia has the very same issue, but even more so. Building it and running the examples is easy. Try to use it as an external library? Try to pull one of those neat examples out of the Skia project and just use it? Your going to need to know a lot more about how the library works. This sort of thing drops the new user squarely on his head. I think Google wants to discourage use of Skia outside there ecosystem to some extent, but I know that's not your intent at all.

I know what you mean. I struggled with Skia just recently. AND that is why I want Elements to be easy to deploy. Copy the starter example, tweak the variables as needed and point to the correct include location and you should be good. The examples should be modular and relocatable.

**Comment by djowel** [comment]
> Each example is a separate mini-project and therefore it should not be considered code duplication. It's like changing `constexpr auto foo = 123; constexpr auto bar = 123;` to have `constexpr auto bar = foo;` while in fact both values are totally separate things and therefore should not be considered to have duplicated code of `123`.

No it is not. It is like template app<class A, class B, class C> { ... }; Then you use it as app<X, Y, Z>; What you are proposing is having everything inside { ... } duplicated.

**Comment by djowel** [comment]
OK, I read the link, @Xeverous. This is a valid and compelling argument: 

"In short: my goal is to make sure the CMakeLists.txt that most people look at and see look and work just like every other one. The less time someone needs to spend learning our custom build system the quicker they can get to real work. Thus how your hide the complexity should be the same way everybody else does if at all possible."

I am still not 100% convinced though. But here's my challenge: show me a complete working starter example that satisfies the first goal: easy deployment. I'm ok if it is more verbose than my original strategy, but not much. I am also OK with some code duplication, but not too much (oh for sure there will be, and I can accept that as another flaw of the cmake language, e.g. no global free functions).

**Comment by Radagan** [comment]
@Xeverous, I gave your minimal sample executable recipe above a try, but I end up with similar errors to before. I also added in the ELEMENT_APP_* and other portions of CMakeMain.txt, but was unable to get a clean compile. The errors revolve around base_view.hpp and support/font.hpp. Maybe I'm jumping the gun, and you just intended that as concept example CMakeLists.txt? 

If so, no worries. I think I need to stop hacking and start figuring out how this all really works. I'm was just excited to start using elements. Modern C++ **really needs** a modern GUI library, and I agree with the core values stated in the elements docs. I would be happy to contribute in the future if that is desired. I have some coming up to speed to do first though.   

Btw, I can test it on Windows 10, Mojave, Catalina, and latest Debian and Ubuntu if need be.

**Comment by Xeverous** [comment]
@Radagan looking closer at your errors, you actually stumbled upon an `#ifdef` problem that was mentioned in #91. It's fixed already but not on master. Try building from the `HEAD` of `develop` branch. Obviously, "it works on my machine" but note that I'm using MinGW when compiling for Windows (which has some `#ifdef` differences).

**Comment by Radagan** [comment]
@Xeverous, indeed, I was pointed at the master branch. I switch to develop and my compile is good, but the linker is unable to resolve:

```LINK Pass 1: command "C:\PROGRA~2\MICROS~2\2019\COMMUN~1\VC\Tools\MSVC\1425~1.286\bin\Hostx86\x86\link.exe /nologo @CMakeFiles\Multimind.dir\objects1.rsp /out:Multimind.exe /implib:Multimind.lib /pdb:C:\Users\Radagan\Development\cpp\Multimind\cmake-build-debug\Multimind.pdb /version:0.0 /machine:X86 /debug /INCREMENTAL /subsystem:console elements\lib\elements.lib C:\Users\Radagan\Development\cpp\libs\elements\lib\external\cairo\lib\x86\cairo.lib C:\Users\Radagan\Development\cpp\libs\elements\lib\external\fontconfig\x86\fontconfig.lib C:\Users\Radagan\Development\cpp\libs\elements\lib\external\freetype\win32\freetype.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:CMakeFiles\Multimind.dir/intermediate.manifest CMakeFiles\Multimind.dir/manifest.res" failed (exit code 1120) with the following output:
elements.lib(app.cpp.obj) : error LNK2019: unresolved external symbol _SetProcessDpiAwareness@4 referenced in function "public: __thiscall cycfi::elements::app::app(int,char * * const)" (??0app@elements@cycfi@@QAE@HQAPAD@Z)```

My CMakeLists.txt is exactly like your example save for changing the name of the project. I'll play with it some more over the weekend.

**Comment by Xeverous** [comment]
This function is one of the newer Windows API functions for DPI-aware programs. MinGW does not support them yet and I just patch them out, if you use MSVC you might be just missing some linker command (or compiling against too old API version?).

**Comment by djowel** [comment]
OK, so sleeping on it, and thinking about it with a fresh mind. Believe me, I always keep an open mind... 

The issue now is DRY vs. code familiarity, as opined by Henry Miller in the link that you gave, which IMO is the most compelling argument thus far against using a cmake include as a template. Is it a substantive argument? No, I don't think so, it is an opinion not really based on technical grounds. 

But suppose I buy into that argument, a fresh look at [CMakeMain.txt](https://github.com/cycfi/elements/blob/master/CMakeMain.txt) shows me that there is absolutely nothing unfamiliar about the script! It is very clear. There are no magic tricks and odd functions.

He further says that:

> The include file needs to handle all the special cases of each example - even cases that only exist for one example - and as a result is much longer than a stand along [sic] CMakeLists.txt. 

I don't think he even read the CMakeMain.txt you linked to because this is not true in this specific example. There are no more special cases here than any other cmake script I have seen (actually there is no code branch at all that depends on a supplied variable, -- most variables are there only to set strings, e.g. ELEMENTS_APP_TITLE and ELEMENTS_APP_COPYRIGHT). 

It is in the literal sense of the word, a "template", and a very simple one! It is even less obscure than the example he gave using the `add_unique_language_file` function.

So, now, I don't think the 'code familiarity' argument holds in this case. I am still not convinced that using cmake includes as templates is a bad idea given the arguments thus far. 

If there are no more arguments other than those stated (*full of variables* and *code familiarity*), can we please make it simple and easy again like what we had before the 'modern' cmake changes?

**Comment by Xeverous** [comment]
I have already modified some examples recipes when rewriting the library's main CMake recipe - examples recipes are already using modern CMake. I have no arguments against current implementation of examples apart from what has already been mentioned.

I'm aware that the topic is controversial (DRY vs clearness) because there are strong arguments for both sides. The utilimate decision is yours as it is your project. I have no need to edit them, I would probably do the thing differently if it was my project, but I understand your decision.

**Comment by djowel** [comment]
> I have already modified some examples recipes when rewriting the library's main CMake recipe - examples recipes are already using modern CMake. I have no arguments against current implementation of examples apart from what has already been mentioned.

Just to be clear, the situation before was that you can easily do an out-of-project build by copying an example, e.g. "empty" into a directory outside elements, edit CMakeLists.txt to have it point to the Element's CMakeMain.txt and it will build and run. It seems that is not the case now. What am I missing?

**Comment by djowel** [comment]
> (DRY vs clearness) because there are strong arguments for both sides

This is a false dichotomy. You can have both.

**Comment by djowel** [comment]
@Xeverous,  so, I am keeping an open mind and had a look at your minimal sample executable cmake recipe using elements you posted above. You know this does not work on MacOS, right? There's nowhere you are setting the bundle info and plist.

**Comment by djowel** [comment]
> > I have already modified some examples recipes when rewriting the library's main CMake recipe - examples recipes are already using modern CMake. I have no arguments against current implementation of examples apart from what has already been mentioned.
> 
> Just to be clear, the situation before was that you can easily do an out-of-project build by copying an example, e.g. "empty" into a directory outside elements, edit CMakeLists.txt to have it point to the Element's CMakeMain.txt and it will build and run. It seems that is not the case now. What am I missing?

OK, I fixed this in develop and master. Now you can copy and paste any of the examples outside the project, set -DELEMENTS_ROOT ="path/to/elements". And the example should immediately build without any hassle.

Of course you can provide your own cmake script any time, but the default should work right out-of-the-box.

**Comment by djowel** [comment]
I added instruction on how to build the examples outside the project: 
http://cycfi.github.io/elements/setup#building-outside-the-project

**Comment by Xeverous** [comment]
> I am keeping an open mind and had a look at your minimal sample executable cmake recipe using elements you posted above. You know this does not work on MacOS, right? There's nowhere you are setting the bundle info and plist.

Yes. I have no idea how these things work on MacOS but I noticed that compared to other systems MacOS requires some extra work in CMake to build some stuff. I have never written anything for MacOS so I just left them out. I guess this is another reason why you prefer to include `CMakeMain.txt` instead of having completely separate recipe for each example.

**Comment by djowel** [comment]
> > I am keeping an open mind and had a look at your minimal sample executable cmake recipe using elements you posted above. You know this does not work on MacOS, right? There's nowhere you are setting the bundle info and plist.
> 
> Yes. I have no idea how these things work on MacOS but I noticed that compared to other systems MacOS requires some extra work in CMake to build some stuff. I have never written anything for MacOS so I just left them out. I guess this is another reason why you prefer to include `CMakeMain.txt` instead of having completely separate recipe for each example.

Exactly. There are also platform specific quirks in all OSes to deal with, as evident in the included CMakeMain.txt (e.g. copying DLLs, etc.) Of course, anyone can just copy the included cmake and use that as the basis for their own projects. But IMO, what's most important is that it should be trouble free to get started ( I insist on the 1-minute-to-get-started requirement :-) ).

I am very open if you have further suggestions or improvements. I do respect your cmake expertise.

**Comment by Radagan** [comment]
@djowel I can confirm that what you checked in works well "out of the box" on Window 10. No more linker errors. I can get started now using elements with a clear distinction between the library and my code. The CMakeList.txt is straightforward up to the include for CMakeMain.txt where the platform specific "magic" undoubtedly takes place. I think you're close to your minute goal with this approach. Thank you both for caring to work on this aspect of the library. Will test on XCode with my app soon. 

@Xeverous Thanks again for that link to the pdf on Modern CMake! CMake's official site should put it at the top of it's documentation pages with a statement like, "New Here? Read this before proceeding!" It's exactly what I haven't found anywhere else.

**Comment by Xeverous** [comment]
> CMake's official site should put it at the top of it's documentation pages

Yes, I know this feeling. The documentation is full of raw information but hardly ever any guidelines.
